version: '3'

vars:
  proj: "./ConfigUpr2.csproj"
  sample: "./sample_package.json"

tasks:
  build:
    desc: "Build the project"
    cmds:
      - dotnet build "{{.proj}}"
    silent: true

  sample:
    desc: "Run against local sample_package.json (test mode)"
    cmds:
      - dotnet run --project "{{.proj}}" -- -t -r "{{.sample}}" -n sample -v 1.2.3

  npm:
    desc: "Run attempting to fetch package.json from a npm package"
    cmds:
      - dotnet run --project "{{.proj}}" -- -n vue

  mermaid:
    desc: "Visualize dependency graph in Mermaid format"
    cmds:
      - dotnet run --project "{{.proj}}" -- -n vue -m
      
  order:
    desc: "Run attempting to fetch package.json from a npm package (Order mode)"
    cmds:
      - dotnet run --project "{{.proj}}" -- -n express -v 3.0.0 -o

  help:
    desc: "Show CLI help"
    cmds:
      - dotnet run --project "{{.proj}}" -- -h
