version: '3'

vars:
  proj: "./ConfigUpr2.csproj"
  sample: "./sample_package.json"

tasks:
  build:
    desc: "Build the project"
    cmds:
      - dotnet build "{{.proj}}"
    silent: true

  run:sample:
    desc: "Run against local sample_package.json (test mode)"
    cmds:
      - dotnet run --project "{{.proj}}" -- -t -r "{{.sample}}" -n sample -v 1.2.3

  run:github:
    desc: "Run attempting to fetch package.json from a example GitHub repo"
    cmds:
      - dotnet run --project "{{.proj}}" -- -n express -r "https://github.com/expressjs/express" -v 2.0.0

  run:registry:
    desc: "Run against npm registry URL pattern"
    cmds:
      - dotnet run --project "{{.proj}}" -- -n express -r "https://registry.npmjs.org/express" -v 2.0.0 
      
  run:order:
    desc: "Run attempting to fetch package.json from a example GitHub repo"
    cmds:
      - dotnet run --project "{{.proj}}" -- -n express -r "https://github.com/expressjs/express" -o

  run:help:
    desc: "Show CLI help"
    cmds:
      - dotnet run --project "{{.proj}}" -- -h
